// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "on save": { 
        "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.",
        "ru": "При сохранении настроек адаптеры будут перезагружены сразу.",
        "en": "When saving settings of the adapters will be restarted immediately."
    },
    "IP": { 
        "de": "IP/ Domain des Emby Servers (mit Port)",
        "ru": "IP / Домен сервера Emby (с портом)",
        "en": "IP/Domain of the Emby server (with port)" },
    "isSSL": { 
        "de": "Verbindung benötigt SSL",
        "ru": "Для подключения требуется SSL",
        "en": "Connection requires SSL" },
    "ApiKey": { 
        "de": "API Key",
        "ru": "Ключ API",
        "en": "API Key" },
    "DeviceIds": { 
        "de": "Geräte Ids die ignoriert werden sollen (Mit Komma getrennt)",
        "ru": "Идентификаторы устройств, которые следует игнорировать (через запятую)",
        "en": "Device Ids to be ignored (comma seperated)" },
    "Timeout": {
        "de": "Verzögerung für Pause/Leerlauf",
        "en": "Delay for pause/idle" },
    "TimeoutDesc": {
        "de": "Nötig wenn mehrere Folgen hintereinander gespielt werden.",
        "en": "Necessary when you watch more episodes in one row." }
};